#!/bin/sh
# Starts and stops securedfamilyd daemon (server side)
#

DAEMON_NAME="sincronizadorCliente.py"
PATH_DAEMON=/home/mboscovich/proyectos/control_parental/cliente
DAEMON=${PATH_DAEMON}/${DAEMON_NAME}
PID=`ps ax|grep ${DAEMON_NAME}|grep -v "grep"|awk '{ print $1 }'`

case "$1" in
start)
	if [ ! ${PID} ];then
	  	echo "Iniciando ${DAEMON_NAME}..."
		cd ${PATH_DAEMON}
		/usr/bin/python ${DAEMON} &
	else
	  	echo "El demonio ya esta en ejecución"
	fi
;;

stop)
	echo "Deteniendo ${DAEMON_NAME}..."
	kill ${PID} &> /dev/null
;;

restart)
  	$0 stop
  	$0 start
;;

status)
             if [ ${PID} ]; then
                     echo "En ejecución..."
		     echo "Consumos del proceso:"
		     echo "--------------------"
		     ps -p ${PID} -o pcpu,pmem
		     echo ""
                     exit 0
             else
                     echo "No esta corriendo"
                     exit 1
             fi
;;

*)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac 	
