#!/bin/sh
# Starts and stops securedfamilyd daemon (server side)
#
### BEGIN INIT INFO
# Provides:          kerberus-cliente
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Kerberus Control Parental
# Description:       Filtro de contenido web.
### END INIT INFO

DAEMON_NAME="kerberus"
PATH_DAEMON=/usr/share/kerberus/cliente
DAEMON=${PATH_DAEMON}/${DAEMON_NAME}
PID=`ps ax|grep ${DAEMON}|grep -v "grep"|tail -n 1|awk '{ print $1 }'`
case "$1" in
start)
	if [ ! ${PID} ];then
	  	echo "Iniciando ${DAEMON_NAME}..."
		${DAEMON} &
		#iptables -A OUTPUT -m owner --uid-owner root -j ACCEPT
		#iptables -A OUTPUT -p tcp --dport 80 -j REJECT
		# Da problemas con messenger
		#iptables -A OUTPUT -p tcp --dport 443 -j REJECT
	else
	  	echo "El demonio ya esta en ejecución"
	fi
;;

stop)
	if [ ${PID} ]; then
	  	echo "Deteniendo ${DAEMON_NAME}..."
		#iptables -D OUTPUT -m owner --uid-owner root -j ACCEPT
		#iptables -D OUTPUT -p tcp --dport 80 -j REJECT
		# Da problemas con messenger
		#iptables -D OUTPUT -p tcp --dport 443 -j REJECT
		kill ${PID} &> /dev/null
	fi
;;

restart)
  	$0 stop
  	$0 start
;;

status)
             if [ ${PID} ]; then
                     echo "En ejecución..."
		     echo "Consumos del proceso:"
		     echo "--------------------"
		     ps -p ${PID} -o pcpu,pmem
		     echo ""
                     exit 0
             else
                     echo "No esta corriendo"
                     exit 1
             fi
;;

*)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac 	
